"""add urgent completion and archive fields

Revision ID: 93f423159ff4
Revises: 082b4e84b175
Create Date: 2026-07-17 20:21:19.295469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f423159ff4'
down_revision: Union[str, Sequence[str], None] = '082b4e84b175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_urgent', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tasks_archived_at'), 'tasks', ['archived_at'], unique=False)
    op.create_index(op.f('ix_tasks_completed_at'), 'tasks', ['completed_at'], unique=False)
    op.create_index(op.f('ix_tasks_is_urgent'), 'tasks', ['is_urgent'], unique=False)
    op.create_check_constraint("check_completed_task_is_done", "tasks", "completed_at IS NULL OR is_done = true")
    op.create_check_constraint("check_archived_task_is_done", "tasks", "archived_at IS NULL OR is_done = true")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_archived_task_is_done", "tasks", type_="check")
    op.drop_constraint("check_completed_task_is_done", "tasks", type_="check")
    op.drop_index(op.f('ix_tasks_is_urgent'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_completed_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_archived_at'), table_name='tasks')
    op.drop_column('tasks', 'archived_at')
    op.drop_column('tasks', 'completed_at')
    op.drop_column('tasks', 'is_urgent')
    # ### end Alembic commands ###
