"""add pending_email to users table

Revision ID: b73d0f97cec7
Revises: 9379220f73b3
Create Date: 2026-07-19 23:34:06.764842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b73d0f97cec7'
down_revision: Union[str, Sequence[str], None] = '9379220f73b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_pending_email'), 'users', ['pending_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_pending_email'), table_name='users')
    op.drop_column('users', 'pending_email')
    # ### end Alembic commands ###
