"""decrease_description_length

Revision ID: dae325d3b50e
Revises: a1b73bfb1a84
Create Date: 2026-07-19 17:29:02.813408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae325d3b50e'
down_revision: Union[str, Sequence[str], None] = 'a1b73bfb1a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=True)
    # ### end Alembic commands ###
